services:
  fhir-validator-core:
    image: infernocommunity/fhir-validator-service:latest
    container_name: fhir-validator-core
    restart: unless-stopped
    ports:
      - "4567:4567"

  fhir-validator-mii:
    image: ghcr.io/medizininformatik-initiative/mii-fhir-validator@sha256:b3200f4c22941bcaffe6ef9a1a2cd34c0d7182b8b60245666b12da32e6272d1f
    container_name: fhir-validator-mii
    restart: unless-stopped
    ports:
      - "8094:8080"
    volumes:
      - mii-fhir-package-cache:/var/cache/fhir-packages
      - ./mii/igs:/opt/validator/igs
      - ./mii/snomed-ct-release:/opt/validator/snomed-ct-release:ro
      - ./mii/certificates:/opt/validator/certificates

volumes:
  mii-fhir-package-cache: